server:
  host: 0.0.0.0
  port: 3000
  logTimezone: Asia/Shanghai
  logTimeFormat: '2006-01-02 15:04:05.000000'
database:
  dsn: root:123456@tcp(127.0.0.1:3306)/awesome?parseTime=true
meilisearch:
  server: http://192.168.123.205:7700
  master_key: