version: "3"
services:
  app:
    image: awesome
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - ./config.yaml:/config.yaml
  worker:
    image: awesome
    restart: always
    command: /worker
    volumes:
      - ./config.yaml:/config.yaml
  scheduler:
    image: awesome
    restart: always
    command: /scheduler
    volumes:
      - ./config.yaml:/config.yaml