server:
  listen: 0.0.0.0:8000
  timezone: Asia/Shanghai
  logTimeFormat: '2006-01-02 15:04:05.000000'

database:
  dsn: root:123456@tcp(192.168.123.205:3306)/awesome?parseTime=true

meilisearch:
  server: http://192.168.123.205:7700
  masterKey:
  batchSize: 10000

redis:
  addr: 127.0.0.1:6379
  password:
  db: 3

sentry:
  dsn: https://7a0a0a10b58c4de3b5567eb329b850c0@sentry.long2ice.io/5
  environment: development