// Code generated by entc, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"entgo.io/ent/dialect/sql"
	"github.com/long2ice/awesome/ent/topiccategory"
)

// TopicCategory is the model entity for the TopicCategory schema.
type TopicCategory struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// Icon holds the value of the "icon" field.
	Icon string `json:"icon,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the TopicCategoryQuery when eager-loading is set.
	Edges TopicCategoryEdges `json:"edges"`
}

// TopicCategoryEdges holds the relations/edges for other nodes in the graph.
type TopicCategoryEdges struct {
	// Topics holds the value of the topics edge.
	Topics []*Topic `json:"topics,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// TopicsOrErr returns the Topics value or an error if the edge
// was not loaded in eager-loading.
func (e TopicCategoryEdges) TopicsOrErr() ([]*Topic, error) {
	if e.loadedTypes[0] {
		return e.Topics, nil
	}
	return nil, &NotLoadedError{edge: "topics"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*TopicCategory) scanValues(columns []string) ([]interface{}, error) {
	values := make([]interface{}, len(columns))
	for i := range columns {
		switch columns[i] {
		case topiccategory.FieldID:
			values[i] = new(sql.NullInt64)
		case topiccategory.FieldName, topiccategory.FieldIcon:
			values[i] = new(sql.NullString)
		default:
			return nil, fmt.Errorf("unexpected column %q for type TopicCategory", columns[i])
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the TopicCategory fields.
func (tc *TopicCategory) assignValues(columns []string, values []interface{}) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case topiccategory.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			tc.ID = int(value.Int64)
		case topiccategory.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				tc.Name = value.String
			}
		case topiccategory.FieldIcon:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field icon", values[i])
			} else if value.Valid {
				tc.Icon = value.String
			}
		}
	}
	return nil
}

// QueryTopics queries the "topics" edge of the TopicCategory entity.
func (tc *TopicCategory) QueryTopics() *TopicQuery {
	return (&TopicCategoryClient{config: tc.config}).QueryTopics(tc)
}

// Update returns a builder for updating this TopicCategory.
// Note that you need to call TopicCategory.Unwrap() before calling this method if this TopicCategory
// was returned from a transaction, and the transaction was committed or rolled back.
func (tc *TopicCategory) Update() *TopicCategoryUpdateOne {
	return (&TopicCategoryClient{config: tc.config}).UpdateOne(tc)
}

// Unwrap unwraps the TopicCategory entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (tc *TopicCategory) Unwrap() *TopicCategory {
	tx, ok := tc.config.driver.(*txDriver)
	if !ok {
		panic("ent: TopicCategory is not a transactional entity")
	}
	tc.config.driver = tx.drv
	return tc
}

// String implements the fmt.Stringer.
func (tc *TopicCategory) String() string {
	var builder strings.Builder
	builder.WriteString("TopicCategory(")
	builder.WriteString(fmt.Sprintf("id=%v", tc.ID))
	builder.WriteString(", name=")
	builder.WriteString(tc.Name)
	builder.WriteString(", icon=")
	builder.WriteString(tc.Icon)
	builder.WriteByte(')')
	return builder.String()
}

// TopicCategories is a parsable slice of TopicCategory.
type TopicCategories []*TopicCategory

func (tc TopicCategories) config(cfg config) {
	for _i := range tc {
		tc[_i].config = cfg
	}
}
