// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/long2ice/awesome/ent/platform"
	"github.com/long2ice/awesome/ent/repo"
	"github.com/long2ice/awesome/ent/topic"
)

// TopicCreate is the builder for creating a Topic entity.
type TopicCreate struct {
	config
	mutation *TopicMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetName sets the "name" field.
func (tc *TopicCreate) SetName(s string) *TopicCreate {
	tc.mutation.SetName(s)
	return tc
}

// SetSubName sets the "sub_name" field.
func (tc *TopicCreate) SetSubName(s string) *TopicCreate {
	tc.mutation.SetSubName(s)
	return tc
}

// SetDescription sets the "description" field.
func (tc *TopicCreate) SetDescription(s string) *TopicCreate {
	tc.mutation.SetDescription(s)
	return tc
}

// SetURL sets the "url" field.
func (tc *TopicCreate) SetURL(s string) *TopicCreate {
	tc.mutation.SetURL(s)
	return tc
}

// SetGithubURL sets the "github_url" field.
func (tc *TopicCreate) SetGithubURL(s string) *TopicCreate {
	tc.mutation.SetGithubURL(s)
	return tc
}

// SetPlatformID sets the "platform_id" field.
func (tc *TopicCreate) SetPlatformID(i int) *TopicCreate {
	tc.mutation.SetPlatformID(i)
	return tc
}

// SetPlatform sets the "platform" edge to the Platform entity.
func (tc *TopicCreate) SetPlatform(p *Platform) *TopicCreate {
	return tc.SetPlatformID(p.ID)
}

// AddRepoIDs adds the "repos" edge to the Repo entity by IDs.
func (tc *TopicCreate) AddRepoIDs(ids ...int) *TopicCreate {
	tc.mutation.AddRepoIDs(ids...)
	return tc
}

// AddRepos adds the "repos" edges to the Repo entity.
func (tc *TopicCreate) AddRepos(r ...*Repo) *TopicCreate {
	ids := make([]int, len(r))
	for i := range r {
		ids[i] = r[i].ID
	}
	return tc.AddRepoIDs(ids...)
}

// Mutation returns the TopicMutation object of the builder.
func (tc *TopicCreate) Mutation() *TopicMutation {
	return tc.mutation
}

// Save creates the Topic in the database.
func (tc *TopicCreate) Save(ctx context.Context) (*Topic, error) {
	return withHooks[*Topic, TopicMutation](ctx, tc.sqlSave, tc.mutation, tc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (tc *TopicCreate) SaveX(ctx context.Context) *Topic {
	v, err := tc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (tc *TopicCreate) Exec(ctx context.Context) error {
	_, err := tc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (tc *TopicCreate) ExecX(ctx context.Context) {
	if err := tc.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (tc *TopicCreate) check() error {
	if _, ok := tc.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "Topic.name"`)}
	}
	if _, ok := tc.mutation.SubName(); !ok {
		return &ValidationError{Name: "sub_name", err: errors.New(`ent: missing required field "Topic.sub_name"`)}
	}
	if _, ok := tc.mutation.Description(); !ok {
		return &ValidationError{Name: "description", err: errors.New(`ent: missing required field "Topic.description"`)}
	}
	if _, ok := tc.mutation.URL(); !ok {
		return &ValidationError{Name: "url", err: errors.New(`ent: missing required field "Topic.url"`)}
	}
	if _, ok := tc.mutation.GithubURL(); !ok {
		return &ValidationError{Name: "github_url", err: errors.New(`ent: missing required field "Topic.github_url"`)}
	}
	if _, ok := tc.mutation.PlatformID(); !ok {
		return &ValidationError{Name: "platform_id", err: errors.New(`ent: missing required field "Topic.platform_id"`)}
	}
	if _, ok := tc.mutation.PlatformID(); !ok {
		return &ValidationError{Name: "platform", err: errors.New(`ent: missing required edge "Topic.platform"`)}
	}
	return nil
}

func (tc *TopicCreate) sqlSave(ctx context.Context) (*Topic, error) {
	if err := tc.check(); err != nil {
		return nil, err
	}
	_node, _spec := tc.createSpec()
	if err := sqlgraph.CreateNode(ctx, tc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	tc.mutation.id = &_node.ID
	tc.mutation.done = true
	return _node, nil
}

func (tc *TopicCreate) createSpec() (*Topic, *sqlgraph.CreateSpec) {
	var (
		_node = &Topic{config: tc.config}
		_spec = sqlgraph.NewCreateSpec(topic.Table, sqlgraph.NewFieldSpec(topic.FieldID, field.TypeInt))
	)
	_spec.OnConflict = tc.conflict
	if value, ok := tc.mutation.Name(); ok {
		_spec.SetField(topic.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := tc.mutation.SubName(); ok {
		_spec.SetField(topic.FieldSubName, field.TypeString, value)
		_node.SubName = value
	}
	if value, ok := tc.mutation.Description(); ok {
		_spec.SetField(topic.FieldDescription, field.TypeString, value)
		_node.Description = value
	}
	if value, ok := tc.mutation.URL(); ok {
		_spec.SetField(topic.FieldURL, field.TypeString, value)
		_node.URL = value
	}
	if value, ok := tc.mutation.GithubURL(); ok {
		_spec.SetField(topic.FieldGithubURL, field.TypeString, value)
		_node.GithubURL = value
	}
	if nodes := tc.mutation.PlatformIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   topic.PlatformTable,
			Columns: []string{topic.PlatformColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: platform.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.PlatformID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := tc.mutation.ReposIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   topic.ReposTable,
			Columns: []string{topic.ReposColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: repo.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Topic.Create().
//		SetName(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.TopicUpsert) {
//			SetName(v+v).
//		}).
//		Exec(ctx)
func (tc *TopicCreate) OnConflict(opts ...sql.ConflictOption) *TopicUpsertOne {
	tc.conflict = opts
	return &TopicUpsertOne{
		create: tc,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Topic.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (tc *TopicCreate) OnConflictColumns(columns ...string) *TopicUpsertOne {
	tc.conflict = append(tc.conflict, sql.ConflictColumns(columns...))
	return &TopicUpsertOne{
		create: tc,
	}
}

type (
	// TopicUpsertOne is the builder for "upsert"-ing
	//  one Topic node.
	TopicUpsertOne struct {
		create *TopicCreate
	}

	// TopicUpsert is the "OnConflict" setter.
	TopicUpsert struct {
		*sql.UpdateSet
	}
)

// SetName sets the "name" field.
func (u *TopicUpsert) SetName(v string) *TopicUpsert {
	u.Set(topic.FieldName, v)
	return u
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *TopicUpsert) UpdateName() *TopicUpsert {
	u.SetExcluded(topic.FieldName)
	return u
}

// SetSubName sets the "sub_name" field.
func (u *TopicUpsert) SetSubName(v string) *TopicUpsert {
	u.Set(topic.FieldSubName, v)
	return u
}

// UpdateSubName sets the "sub_name" field to the value that was provided on create.
func (u *TopicUpsert) UpdateSubName() *TopicUpsert {
	u.SetExcluded(topic.FieldSubName)
	return u
}

// SetDescription sets the "description" field.
func (u *TopicUpsert) SetDescription(v string) *TopicUpsert {
	u.Set(topic.FieldDescription, v)
	return u
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *TopicUpsert) UpdateDescription() *TopicUpsert {
	u.SetExcluded(topic.FieldDescription)
	return u
}

// SetURL sets the "url" field.
func (u *TopicUpsert) SetURL(v string) *TopicUpsert {
	u.Set(topic.FieldURL, v)
	return u
}

// UpdateURL sets the "url" field to the value that was provided on create.
func (u *TopicUpsert) UpdateURL() *TopicUpsert {
	u.SetExcluded(topic.FieldURL)
	return u
}

// SetGithubURL sets the "github_url" field.
func (u *TopicUpsert) SetGithubURL(v string) *TopicUpsert {
	u.Set(topic.FieldGithubURL, v)
	return u
}

// UpdateGithubURL sets the "github_url" field to the value that was provided on create.
func (u *TopicUpsert) UpdateGithubURL() *TopicUpsert {
	u.SetExcluded(topic.FieldGithubURL)
	return u
}

// SetPlatformID sets the "platform_id" field.
func (u *TopicUpsert) SetPlatformID(v int) *TopicUpsert {
	u.Set(topic.FieldPlatformID, v)
	return u
}

// UpdatePlatformID sets the "platform_id" field to the value that was provided on create.
func (u *TopicUpsert) UpdatePlatformID() *TopicUpsert {
	u.SetExcluded(topic.FieldPlatformID)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.Topic.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *TopicUpsertOne) UpdateNewValues() *TopicUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Topic.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *TopicUpsertOne) Ignore() *TopicUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *TopicUpsertOne) DoNothing() *TopicUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the TopicCreate.OnConflict
// documentation for more info.
func (u *TopicUpsertOne) Update(set func(*TopicUpsert)) *TopicUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&TopicUpsert{UpdateSet: update})
	}))
	return u
}

// SetName sets the "name" field.
func (u *TopicUpsertOne) SetName(v string) *TopicUpsertOne {
	return u.Update(func(s *TopicUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *TopicUpsertOne) UpdateName() *TopicUpsertOne {
	return u.Update(func(s *TopicUpsert) {
		s.UpdateName()
	})
}

// SetSubName sets the "sub_name" field.
func (u *TopicUpsertOne) SetSubName(v string) *TopicUpsertOne {
	return u.Update(func(s *TopicUpsert) {
		s.SetSubName(v)
	})
}

// UpdateSubName sets the "sub_name" field to the value that was provided on create.
func (u *TopicUpsertOne) UpdateSubName() *TopicUpsertOne {
	return u.Update(func(s *TopicUpsert) {
		s.UpdateSubName()
	})
}

// SetDescription sets the "description" field.
func (u *TopicUpsertOne) SetDescription(v string) *TopicUpsertOne {
	return u.Update(func(s *TopicUpsert) {
		s.SetDescription(v)
	})
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *TopicUpsertOne) UpdateDescription() *TopicUpsertOne {
	return u.Update(func(s *TopicUpsert) {
		s.UpdateDescription()
	})
}

// SetURL sets the "url" field.
func (u *TopicUpsertOne) SetURL(v string) *TopicUpsertOne {
	return u.Update(func(s *TopicUpsert) {
		s.SetURL(v)
	})
}

// UpdateURL sets the "url" field to the value that was provided on create.
func (u *TopicUpsertOne) UpdateURL() *TopicUpsertOne {
	return u.Update(func(s *TopicUpsert) {
		s.UpdateURL()
	})
}

// SetGithubURL sets the "github_url" field.
func (u *TopicUpsertOne) SetGithubURL(v string) *TopicUpsertOne {
	return u.Update(func(s *TopicUpsert) {
		s.SetGithubURL(v)
	})
}

// UpdateGithubURL sets the "github_url" field to the value that was provided on create.
func (u *TopicUpsertOne) UpdateGithubURL() *TopicUpsertOne {
	return u.Update(func(s *TopicUpsert) {
		s.UpdateGithubURL()
	})
}

// SetPlatformID sets the "platform_id" field.
func (u *TopicUpsertOne) SetPlatformID(v int) *TopicUpsertOne {
	return u.Update(func(s *TopicUpsert) {
		s.SetPlatformID(v)
	})
}

// UpdatePlatformID sets the "platform_id" field to the value that was provided on create.
func (u *TopicUpsertOne) UpdatePlatformID() *TopicUpsertOne {
	return u.Update(func(s *TopicUpsert) {
		s.UpdatePlatformID()
	})
}

// Exec executes the query.
func (u *TopicUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for TopicCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *TopicUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *TopicUpsertOne) ID(ctx context.Context) (id int, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *TopicUpsertOne) IDX(ctx context.Context) int {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// TopicCreateBulk is the builder for creating many Topic entities in bulk.
type TopicCreateBulk struct {
	config
	builders []*TopicCreate
	conflict []sql.ConflictOption
}

// Save creates the Topic entities in the database.
func (tcb *TopicCreateBulk) Save(ctx context.Context) ([]*Topic, error) {
	specs := make([]*sqlgraph.CreateSpec, len(tcb.builders))
	nodes := make([]*Topic, len(tcb.builders))
	mutators := make([]Mutator, len(tcb.builders))
	for i := range tcb.builders {
		func(i int, root context.Context) {
			builder := tcb.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*TopicMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				nodes[i], specs[i] = builder.createSpec()
				var err error
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, tcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = tcb.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, tcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, tcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (tcb *TopicCreateBulk) SaveX(ctx context.Context) []*Topic {
	v, err := tcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (tcb *TopicCreateBulk) Exec(ctx context.Context) error {
	_, err := tcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (tcb *TopicCreateBulk) ExecX(ctx context.Context) {
	if err := tcb.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Topic.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.TopicUpsert) {
//			SetName(v+v).
//		}).
//		Exec(ctx)
func (tcb *TopicCreateBulk) OnConflict(opts ...sql.ConflictOption) *TopicUpsertBulk {
	tcb.conflict = opts
	return &TopicUpsertBulk{
		create: tcb,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Topic.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (tcb *TopicCreateBulk) OnConflictColumns(columns ...string) *TopicUpsertBulk {
	tcb.conflict = append(tcb.conflict, sql.ConflictColumns(columns...))
	return &TopicUpsertBulk{
		create: tcb,
	}
}

// TopicUpsertBulk is the builder for "upsert"-ing
// a bulk of Topic nodes.
type TopicUpsertBulk struct {
	create *TopicCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.Topic.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *TopicUpsertBulk) UpdateNewValues() *TopicUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Topic.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *TopicUpsertBulk) Ignore() *TopicUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *TopicUpsertBulk) DoNothing() *TopicUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the TopicCreateBulk.OnConflict
// documentation for more info.
func (u *TopicUpsertBulk) Update(set func(*TopicUpsert)) *TopicUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&TopicUpsert{UpdateSet: update})
	}))
	return u
}

// SetName sets the "name" field.
func (u *TopicUpsertBulk) SetName(v string) *TopicUpsertBulk {
	return u.Update(func(s *TopicUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *TopicUpsertBulk) UpdateName() *TopicUpsertBulk {
	return u.Update(func(s *TopicUpsert) {
		s.UpdateName()
	})
}

// SetSubName sets the "sub_name" field.
func (u *TopicUpsertBulk) SetSubName(v string) *TopicUpsertBulk {
	return u.Update(func(s *TopicUpsert) {
		s.SetSubName(v)
	})
}

// UpdateSubName sets the "sub_name" field to the value that was provided on create.
func (u *TopicUpsertBulk) UpdateSubName() *TopicUpsertBulk {
	return u.Update(func(s *TopicUpsert) {
		s.UpdateSubName()
	})
}

// SetDescription sets the "description" field.
func (u *TopicUpsertBulk) SetDescription(v string) *TopicUpsertBulk {
	return u.Update(func(s *TopicUpsert) {
		s.SetDescription(v)
	})
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *TopicUpsertBulk) UpdateDescription() *TopicUpsertBulk {
	return u.Update(func(s *TopicUpsert) {
		s.UpdateDescription()
	})
}

// SetURL sets the "url" field.
func (u *TopicUpsertBulk) SetURL(v string) *TopicUpsertBulk {
	return u.Update(func(s *TopicUpsert) {
		s.SetURL(v)
	})
}

// UpdateURL sets the "url" field to the value that was provided on create.
func (u *TopicUpsertBulk) UpdateURL() *TopicUpsertBulk {
	return u.Update(func(s *TopicUpsert) {
		s.UpdateURL()
	})
}

// SetGithubURL sets the "github_url" field.
func (u *TopicUpsertBulk) SetGithubURL(v string) *TopicUpsertBulk {
	return u.Update(func(s *TopicUpsert) {
		s.SetGithubURL(v)
	})
}

// UpdateGithubURL sets the "github_url" field to the value that was provided on create.
func (u *TopicUpsertBulk) UpdateGithubURL() *TopicUpsertBulk {
	return u.Update(func(s *TopicUpsert) {
		s.UpdateGithubURL()
	})
}

// SetPlatformID sets the "platform_id" field.
func (u *TopicUpsertBulk) SetPlatformID(v int) *TopicUpsertBulk {
	return u.Update(func(s *TopicUpsert) {
		s.SetPlatformID(v)
	})
}

// UpdatePlatformID sets the "platform_id" field to the value that was provided on create.
func (u *TopicUpsertBulk) UpdatePlatformID() *TopicUpsertBulk {
	return u.Update(func(s *TopicUpsert) {
		s.UpdatePlatformID()
	})
}

// Exec executes the query.
func (u *TopicUpsertBulk) Exec(ctx context.Context) error {
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the TopicCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for TopicCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *TopicUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
