// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/long2ice/awesome/ent/platform"
	"github.com/long2ice/awesome/ent/predicate"
	"github.com/long2ice/awesome/ent/repo"
	"github.com/long2ice/awesome/ent/topic"
)

// TopicUpdate is the builder for updating Topic entities.
type TopicUpdate struct {
	config
	hooks     []Hook
	mutation  *TopicMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the TopicUpdate builder.
func (tu *TopicUpdate) Where(ps ...predicate.Topic) *TopicUpdate {
	tu.mutation.Where(ps...)
	return tu
}

// SetName sets the "name" field.
func (tu *TopicUpdate) SetName(s string) *TopicUpdate {
	tu.mutation.SetName(s)
	return tu
}

// SetSubName sets the "sub_name" field.
func (tu *TopicUpdate) SetSubName(s string) *TopicUpdate {
	tu.mutation.SetSubName(s)
	return tu
}

// SetDescription sets the "description" field.
func (tu *TopicUpdate) SetDescription(s string) *TopicUpdate {
	tu.mutation.SetDescription(s)
	return tu
}

// SetURL sets the "url" field.
func (tu *TopicUpdate) SetURL(s string) *TopicUpdate {
	tu.mutation.SetURL(s)
	return tu
}

// SetGithubURL sets the "github_url" field.
func (tu *TopicUpdate) SetGithubURL(s string) *TopicUpdate {
	tu.mutation.SetGithubURL(s)
	return tu
}

// SetPlatformID sets the "platform_id" field.
func (tu *TopicUpdate) SetPlatformID(i int) *TopicUpdate {
	tu.mutation.SetPlatformID(i)
	return tu
}

// SetPlatform sets the "platform" edge to the Platform entity.
func (tu *TopicUpdate) SetPlatform(p *Platform) *TopicUpdate {
	return tu.SetPlatformID(p.ID)
}

// AddRepoIDs adds the "repos" edge to the Repo entity by IDs.
func (tu *TopicUpdate) AddRepoIDs(ids ...int) *TopicUpdate {
	tu.mutation.AddRepoIDs(ids...)
	return tu
}

// AddRepos adds the "repos" edges to the Repo entity.
func (tu *TopicUpdate) AddRepos(r ...*Repo) *TopicUpdate {
	ids := make([]int, len(r))
	for i := range r {
		ids[i] = r[i].ID
	}
	return tu.AddRepoIDs(ids...)
}

// Mutation returns the TopicMutation object of the builder.
func (tu *TopicUpdate) Mutation() *TopicMutation {
	return tu.mutation
}

// ClearPlatform clears the "platform" edge to the Platform entity.
func (tu *TopicUpdate) ClearPlatform() *TopicUpdate {
	tu.mutation.ClearPlatform()
	return tu
}

// ClearRepos clears all "repos" edges to the Repo entity.
func (tu *TopicUpdate) ClearRepos() *TopicUpdate {
	tu.mutation.ClearRepos()
	return tu
}

// RemoveRepoIDs removes the "repos" edge to Repo entities by IDs.
func (tu *TopicUpdate) RemoveRepoIDs(ids ...int) *TopicUpdate {
	tu.mutation.RemoveRepoIDs(ids...)
	return tu
}

// RemoveRepos removes "repos" edges to Repo entities.
func (tu *TopicUpdate) RemoveRepos(r ...*Repo) *TopicUpdate {
	ids := make([]int, len(r))
	for i := range r {
		ids[i] = r[i].ID
	}
	return tu.RemoveRepoIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (tu *TopicUpdate) Save(ctx context.Context) (int, error) {
	return withHooks[int, TopicMutation](ctx, tu.sqlSave, tu.mutation, tu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (tu *TopicUpdate) SaveX(ctx context.Context) int {
	affected, err := tu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (tu *TopicUpdate) Exec(ctx context.Context) error {
	_, err := tu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (tu *TopicUpdate) ExecX(ctx context.Context) {
	if err := tu.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (tu *TopicUpdate) check() error {
	if _, ok := tu.mutation.PlatformID(); tu.mutation.PlatformCleared() && !ok {
		return errors.New(`ent: clearing a required unique edge "Topic.platform"`)
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (tu *TopicUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *TopicUpdate {
	tu.modifiers = append(tu.modifiers, modifiers...)
	return tu
}

func (tu *TopicUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := tu.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(topic.Table, topic.Columns, sqlgraph.NewFieldSpec(topic.FieldID, field.TypeInt))
	if ps := tu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := tu.mutation.Name(); ok {
		_spec.SetField(topic.FieldName, field.TypeString, value)
	}
	if value, ok := tu.mutation.SubName(); ok {
		_spec.SetField(topic.FieldSubName, field.TypeString, value)
	}
	if value, ok := tu.mutation.Description(); ok {
		_spec.SetField(topic.FieldDescription, field.TypeString, value)
	}
	if value, ok := tu.mutation.URL(); ok {
		_spec.SetField(topic.FieldURL, field.TypeString, value)
	}
	if value, ok := tu.mutation.GithubURL(); ok {
		_spec.SetField(topic.FieldGithubURL, field.TypeString, value)
	}
	if tu.mutation.PlatformCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   topic.PlatformTable,
			Columns: []string{topic.PlatformColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: platform.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := tu.mutation.PlatformIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   topic.PlatformTable,
			Columns: []string{topic.PlatformColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: platform.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if tu.mutation.ReposCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   topic.ReposTable,
			Columns: []string{topic.ReposColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: repo.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := tu.mutation.RemovedReposIDs(); len(nodes) > 0 && !tu.mutation.ReposCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   topic.ReposTable,
			Columns: []string{topic.ReposColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: repo.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := tu.mutation.ReposIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   topic.ReposTable,
			Columns: []string{topic.ReposColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: repo.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(tu.modifiers...)
	if n, err = sqlgraph.UpdateNodes(ctx, tu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{topic.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	tu.mutation.done = true
	return n, nil
}

// TopicUpdateOne is the builder for updating a single Topic entity.
type TopicUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *TopicMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetName sets the "name" field.
func (tuo *TopicUpdateOne) SetName(s string) *TopicUpdateOne {
	tuo.mutation.SetName(s)
	return tuo
}

// SetSubName sets the "sub_name" field.
func (tuo *TopicUpdateOne) SetSubName(s string) *TopicUpdateOne {
	tuo.mutation.SetSubName(s)
	return tuo
}

// SetDescription sets the "description" field.
func (tuo *TopicUpdateOne) SetDescription(s string) *TopicUpdateOne {
	tuo.mutation.SetDescription(s)
	return tuo
}

// SetURL sets the "url" field.
func (tuo *TopicUpdateOne) SetURL(s string) *TopicUpdateOne {
	tuo.mutation.SetURL(s)
	return tuo
}

// SetGithubURL sets the "github_url" field.
func (tuo *TopicUpdateOne) SetGithubURL(s string) *TopicUpdateOne {
	tuo.mutation.SetGithubURL(s)
	return tuo
}

// SetPlatformID sets the "platform_id" field.
func (tuo *TopicUpdateOne) SetPlatformID(i int) *TopicUpdateOne {
	tuo.mutation.SetPlatformID(i)
	return tuo
}

// SetPlatform sets the "platform" edge to the Platform entity.
func (tuo *TopicUpdateOne) SetPlatform(p *Platform) *TopicUpdateOne {
	return tuo.SetPlatformID(p.ID)
}

// AddRepoIDs adds the "repos" edge to the Repo entity by IDs.
func (tuo *TopicUpdateOne) AddRepoIDs(ids ...int) *TopicUpdateOne {
	tuo.mutation.AddRepoIDs(ids...)
	return tuo
}

// AddRepos adds the "repos" edges to the Repo entity.
func (tuo *TopicUpdateOne) AddRepos(r ...*Repo) *TopicUpdateOne {
	ids := make([]int, len(r))
	for i := range r {
		ids[i] = r[i].ID
	}
	return tuo.AddRepoIDs(ids...)
}

// Mutation returns the TopicMutation object of the builder.
func (tuo *TopicUpdateOne) Mutation() *TopicMutation {
	return tuo.mutation
}

// ClearPlatform clears the "platform" edge to the Platform entity.
func (tuo *TopicUpdateOne) ClearPlatform() *TopicUpdateOne {
	tuo.mutation.ClearPlatform()
	return tuo
}

// ClearRepos clears all "repos" edges to the Repo entity.
func (tuo *TopicUpdateOne) ClearRepos() *TopicUpdateOne {
	tuo.mutation.ClearRepos()
	return tuo
}

// RemoveRepoIDs removes the "repos" edge to Repo entities by IDs.
func (tuo *TopicUpdateOne) RemoveRepoIDs(ids ...int) *TopicUpdateOne {
	tuo.mutation.RemoveRepoIDs(ids...)
	return tuo
}

// RemoveRepos removes "repos" edges to Repo entities.
func (tuo *TopicUpdateOne) RemoveRepos(r ...*Repo) *TopicUpdateOne {
	ids := make([]int, len(r))
	for i := range r {
		ids[i] = r[i].ID
	}
	return tuo.RemoveRepoIDs(ids...)
}

// Where appends a list predicates to the TopicUpdate builder.
func (tuo *TopicUpdateOne) Where(ps ...predicate.Topic) *TopicUpdateOne {
	tuo.mutation.Where(ps...)
	return tuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (tuo *TopicUpdateOne) Select(field string, fields ...string) *TopicUpdateOne {
	tuo.fields = append([]string{field}, fields...)
	return tuo
}

// Save executes the query and returns the updated Topic entity.
func (tuo *TopicUpdateOne) Save(ctx context.Context) (*Topic, error) {
	return withHooks[*Topic, TopicMutation](ctx, tuo.sqlSave, tuo.mutation, tuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (tuo *TopicUpdateOne) SaveX(ctx context.Context) *Topic {
	node, err := tuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (tuo *TopicUpdateOne) Exec(ctx context.Context) error {
	_, err := tuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (tuo *TopicUpdateOne) ExecX(ctx context.Context) {
	if err := tuo.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (tuo *TopicUpdateOne) check() error {
	if _, ok := tuo.mutation.PlatformID(); tuo.mutation.PlatformCleared() && !ok {
		return errors.New(`ent: clearing a required unique edge "Topic.platform"`)
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (tuo *TopicUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *TopicUpdateOne {
	tuo.modifiers = append(tuo.modifiers, modifiers...)
	return tuo
}

func (tuo *TopicUpdateOne) sqlSave(ctx context.Context) (_node *Topic, err error) {
	if err := tuo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(topic.Table, topic.Columns, sqlgraph.NewFieldSpec(topic.FieldID, field.TypeInt))
	id, ok := tuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Topic.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := tuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, topic.FieldID)
		for _, f := range fields {
			if !topic.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != topic.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := tuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := tuo.mutation.Name(); ok {
		_spec.SetField(topic.FieldName, field.TypeString, value)
	}
	if value, ok := tuo.mutation.SubName(); ok {
		_spec.SetField(topic.FieldSubName, field.TypeString, value)
	}
	if value, ok := tuo.mutation.Description(); ok {
		_spec.SetField(topic.FieldDescription, field.TypeString, value)
	}
	if value, ok := tuo.mutation.URL(); ok {
		_spec.SetField(topic.FieldURL, field.TypeString, value)
	}
	if value, ok := tuo.mutation.GithubURL(); ok {
		_spec.SetField(topic.FieldGithubURL, field.TypeString, value)
	}
	if tuo.mutation.PlatformCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   topic.PlatformTable,
			Columns: []string{topic.PlatformColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: platform.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := tuo.mutation.PlatformIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   topic.PlatformTable,
			Columns: []string{topic.PlatformColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: platform.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if tuo.mutation.ReposCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   topic.ReposTable,
			Columns: []string{topic.ReposColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: repo.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := tuo.mutation.RemovedReposIDs(); len(nodes) > 0 && !tuo.mutation.ReposCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   topic.ReposTable,
			Columns: []string{topic.ReposColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: repo.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := tuo.mutation.ReposIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   topic.ReposTable,
			Columns: []string{topic.ReposColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: repo.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(tuo.modifiers...)
	_node = &Topic{config: tuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, tuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{topic.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	tuo.mutation.done = true
	return _node, nil
}
