// Code generated by entc, DO NOT EDIT.

package platform

const (
	// Label holds the string label denoting the platform type in the database.
	Label = "platform"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldIcon holds the string denoting the icon field in the database.
	FieldIcon = "icon"
	// EdgeTopics holds the string denoting the topics edge name in mutations.
	EdgeTopics = "topics"
	// Table holds the table name of the platform in the database.
	Table = "platform"
	// TopicsTable is the table that holds the topics relation/edge.
	TopicsTable = "topic"
	// TopicsInverseTable is the table name for the Topic entity.
	// It exists in this package in order to avoid circular dependency with the "topic" package.
	TopicsInverseTable = "topic"
	// TopicsColumn is the table column denoting the topics relation/edge.
	TopicsColumn = "platform_id"
)

// Columns holds all SQL columns for platform fields.
var Columns = []string{
	FieldID,
	FieldName,
	FieldIcon,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}
