// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Project is the predicate function for project builders.
type Project func(*sql.Selector)

// Topic is the predicate function for topic builders.
type Topic func(*sql.Selector)

// TopicCategory is the predicate function for topiccategory builders.
type TopicCategory func(*sql.Selector)
