// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Platform is the predicate function for platform builders.
type Platform func(*sql.Selector)

// Repo is the predicate function for repo builders.
type Repo func(*sql.Selector)

// Topic is the predicate function for topic builders.
type Topic func(*sql.Selector)
